### ISSUE TITLE
run 

### ISSUE THREAD

**Issue by salman404** [ab28dev/instagram-username-checker#1]
How can run it . example command line

**Comment by ab28dev** [comment]
I will upload a README soon for this. And for the time mean you can run it by following the instructions below:-
1. Install vscode editor
2. Install python 2 ( as python 3 sometimes causes some import error for selenium). Remember to tick the box saying " Add to path ".
3. Now open vscode
4. Install recommend python tool
5. Set the interpreter by clicking on the bottom left corner of the window.
6. Now open the folder ( the repository) in the editor by selecting open folder option.
7. Now open a terminal from editor
8. run the file using this command - "python main.py
